### PR TITLE
Convert advect_base.F90 routines to C++

### PR DESCRIPTION
**Pull request by harpolea**
This converts the routines in `advect_base.F90` and `make_edge_scal.F90` to C++. It also converts a couple of the routines in `base_state_geometry.F90` in order to do base state restriction and ghost filling. 

The indexing of the 1d base states is quite messy at the moment, but should become clearer when we switch to storing the base state as a Vector of RealVectors. 

This should not change the results of single level problems. Testing 3d reacting_bubble with 3 levels gives no changes for `ppm_type=0`, and small round-off level changes for types 1 and 2. It compiles and runs on the GPU.

### CODE REVIEW

**Comment by adam-m-jcbs** [comment]
Resolved the conflict (it appeared to just be an extra space).  Didn't mean to merge the resolution, but hopefully deleting a space doesn't break anything.

**Comment by adam-m-jcbs** [comment]
@harpolea did my accidental merge break this (commit 6259bc4: https://github.com/AMReX-Astro/MAESTROeX/pull/148/commits/6259bc4cf0e4cd4471f657c802b71cd0c8c89470 )?  It shouldn't have, but I've learned things that shouldn't break often do.  

If I broke your code, I'm incredibly sorry and would be happy to help getting things working again.

**Comment by harpolea** [comment]
@adam-m-jcbs It still runs and compiles, so I think the merge is ok! Travis is complaining because I've now told it to fail if the clang static analysis finds anything

**Comment by zingale** [comment]
test results:
http://groot.astro.sunysb.edu/MAESTROeX/test-suite/gfortran/2020-02-11-002/index.html

**Comment by zingale** [comment]
updated tests:
http://groot.astro.sunysb.edu/MAESTROeX/test-suite/gfortran/2020-02-14-001/index.html

**Pull request merged**
