### PR TITLE
Ported deltagamma from MAESTRO

### PR DESCRIPTION
**Pull request by harpolea**
Ported the deltagamma stuff from MAESTRO, addressing #13 

This mainly involved updating MaestroMakeS.cpp and make_S.F90 to include deltagamma in calculations of the rhs of the divergence constraint.

### CODE REVIEW

**Comment by zingale** [comment]
a long time ago, we had a test problem for this.  Here's a figure from a paper draft that never saw the light of day.  This used the `double_bubble` setup with the `multigamma` EOS.  Can you see if you see this sort of difference with the ported delta gamma?

dgamma

**Comment by harpolea** [comment]
This is a plot of the magnitude of the gradient of rhoh - on the left is with deltagamma, on the right without. This looks to be roughly in line with the other figure?

deltagamma_vs_without

**Comment by zingale** [comment]
Indeed, very nice

**Comment by zingale** [comment]
this looks good to me.  @ajnonaka can you run the MAESTROeX test suite on this pull request?

**Comment by ajnonaka** [comment]
Regression test came out clean.  I'll merge into development.

**Pull request merged**
