### PR TITLE
Tiling

### PR DESCRIPTION
**Pull request by harpolea**
Implements OpenMP/tiling for MFIter loops, addressing #3 

Compared outputs of rt and incomp_shear_jet using AMReX's fcompare script (OMP vs MPI and OMP vs serial) - plotfiles agree.

### CODE REVIEW

**Comment by harpolea** [comment]
Repeated both tests for 2x resolution - plots agree for rt, agree to 1e-13 - 1e-14 abs/rel error for incomp_shear_jet

**Comment by zingale** [comment]
can you try the test that showed some variation with the `system.regtest_reduction` flag?

> We have added a new flag -- system::regtest_reduction -- that controls whether or not we use the OpenMP reduction.  In AMReX_MultiFab we have replaced "pragma omp parallel reduction(+:sm)" by "pragma omp parallel if (!system::regtest_reduction) reduction(+:sm)" so that if you set system.regtest_reduction = 1 in your inputs file (or command line), you will not see the OpenMP-related variability in MultiFab sum and norm1.  You can also use this in your application code.

**Comment by harpolea** [comment]
I'm still getting differences (and since I merged with the latest development branch updates they've got worse) - I'll try turning some of the tiling off and see if I can locate the bug(s)

**Comment by zingale** [comment]
@doreenfan @ajnonaka can one of you take a look at this PR?  Alice has things agreeing with development now.  I'll also look at it.

**Comment by doreenfan** [comment]
It looks good! I just ran wdconvect without randomly generated velocities and the solutions match the ones from development branch, and runtime was faster with more threads.

**Comment by ajnonaka** [comment]
I'm going to merge the tiling branch into development, and then merge development into master as part of git merge day.  Unless anybody has objections?  I also want to add some OpenMP tests to the regression suite.

**Comment by zingale** [comment]
works for me!

**Pull request merged**
