### PR TITLE
add some color to the output

### PR DESCRIPTION
**Pull request by zingale**

### CODE REVIEW

**Comment by zingale** [comment]
we might want to output some of the warnings in the base state stuff as orange, but right now, we manage those through the simple_log.  See #464

**Comment by zingale** [comment]
this is what the output looks like with this PR:

image

**Comment by biboyd** [comment]
This looks good, outside those warnings there is an error message in `MaestroBurner.cpp` we might want to make red
https://github.com/AMReX-Astro/MAESTROeX/blob/e714207d0d102435e876bc33b3a8c573c982ad70/Source/MaestroBurner.cpp#L193

**Comment by zingale** [comment]
updated the burner error

**Comment by zingale** [comment]
actually, should we really be using `amrex::Print()` in the burner?  I think that code is run on all processors, so the processor that has the problem should output it.

**Review by biboyd — APPROVED** [review]
All looks good to me now

**Pull request merged**
