### PR TITLE
add wdconvect CI

### PR DESCRIPTION
**Pull request by zingale**

### CODE REVIEW

**Comment by zingale** [comment]
this gives diffs in the last digit.  Not sure why...

**Comment by biboyd** [comment]
When I run on my machine I get 

```
 vort                         3.7905619114e-13         0.089547619929
 pioverp0                    -1.3133053276e-05       1.3515909745e-05
 circ_velocity                2.4305549801e-15           273571.94181
```
which agrees with the CI calculation. Seems the benchmark is just off by a bit

**Comment by zingale** [comment]
probably the compiler version -- I'm using GCC 14.1.  I think the CI is using 11.4.

Let me try bumping up the Ubuntu here

**Comment by zingale** [comment]
okay it passes if we run with Ubuntu 24.04 which uses GCC 13.2.

**Pull request merged**
