### PR TITLE
BaseState-ifying base state 1/n

### PR DESCRIPTION
**Pull request by harpolea**
This converts some of the existing base state variables to `BaseState` objects. It should be merged after #176, and should not change the output.

### CODE REVIEW

**Comment by harpolea** [comment]
This shouldn't be merged yet - I've discovered there's a bug in 359a775 which has broken the GPU evolution which I'm currently trying to fix

**Comment by harpolea** [comment]
GPU bug should be fixed by 8491eba

**Comment by doreenfan** [comment]
BaseState variables used to construct the coefficients for Tridiag solve cannot currently be initialized on GPU. I believe this problem will be solved in future pull requests (m/n), so those variables will be put back onto GPUs then.

**Comment by doreenfan** [comment]
Some non-negligible diffs are seen in velocity output at `t=0` when running wdconvect `inputs_3d_amr_regression` with burning off. This is with 4 MPI and no OMP. Interestingly, `inputs_omp_3d_regression` with 2 MPI + 2 OMP produces zero diffs even though it is also a multilevel test. It seems that `ppm_type` is at least partially responsible, but I don't see any bugs in that part of the code.  
```
 L0 norm of Absolute and Relative Error in Each Component
--------------------------------------------------------------------------------
Level:  0
                              velx:           70.6189853         2277.163942
                              vely:          95.50275818         13958.26364
                              velz:          79.44284417         14401.18797
                            magvel:          99.37509668         20.17530206
                          momentum:          40842690.47         20.17530206
                              vort:      1.565681478e-06         1970.395459
                               rho:                    0                   0
                              rhoh:                    0                   0
                                 h:                    0                   0
                         rhoX(C12):                    0                   0
                         rhoX(O16):                    0                   0
                         rhoX(ash):                    0                   0
                            tfromp:                    0                   0
                            tfromh:                    0                   0
                            deltap:                    0                   0
                            deltaT:                    0                   0
                                Pi:       4.53017652e+17         11336.63627
                          pioverp0:      5.238670238e-05         11336.63627
                          p0pluspi:      4.530177572e+17     5.238664444e-05
                           rhopert:                    0                   0
                          rhohpert:                    0                   0
                             tpert:                    0                   0
                        MachNumber:      9.245855501e-07         20.98710215
                        deltagamma:                    0                   0
                           entropy:                    0                   0
                       entropypert:                    0                   0
                                 S:                    0                   0
                           thermal:                    0                   0
                      conductivity:                    0                   0
                   radial_velocity:          98.94730338         1097.590708
                     circ_velocity:          58.68001402                 inf
                            sponge:                    0                   0

Level:  1
                              velx:          85.03936486         13086.26313
                              vely:          106.1092159         2878.643811
                              velz:          97.99196563         5175.265803
                            magvel:           108.709919         4.089721702
                          momentum:          42346281.72         4.089721702
                              vort:      3.110372356e-06         859.5994195
                               rho:                    0                   0
                              rhoh:                    0                   0
                                 h:                    0                   0
                         rhoX(C12):                    0                   0
                         rhoX(O16):                    0                   0
                         rhoX(ash):                    0                   0
                            tfromp:                    0                   0
                            tfromh:                    0                   0
                            deltap:                    0                   0
                            deltaT:                    0                   0
                                Pi:      4.736563192e+17          183465.564
                          pioverp0:      5.318299094e-05          183465.564
                          p0pluspi:      4.736561402e+17     5.318294125e-05
                           rhopert:                    0                   0
                          rhohpert:                    0                   0
                             tpert:                    0                   0
                        MachNumber:      1.011433015e-06         4.090708924
                        deltagamma:                    0                   0
                           entropy:                    0                   0
                       entropypert:                    0                   0
                                 S:                    0                   0
                           thermal:                    0                   0
                      conductivity:                    0                   0
                   radial_velocity:          108.1215159         72799.22973
                     circ_velocity:          81.58682908         195.6385231
                            sponge:                    0                   0

Level:  2
                              velx:          61.06179413         1587.655778
                              vely:          51.95540775         2897.642364
                              velz:          64.00936453          12080.9858
                            magvel:          61.35744551         2.477036901
                          momentum:          43083936.27         2.477036901
                              vort:      3.473546862e-06         308.4012683
                               rho:                    0                   0
                              rhoh:                    0                   0
                                 h:                    0                   0
                         rhoX(C12):                    0                   0
                         rhoX(O16):                    0                   0
                         rhoX(ash):                    0                   0
                            tfromp:                    0                   0
                            tfromh:                    0                   0
                            deltap:                    0                   0
                            deltaT:                    0                   0
                                Pi:      4.760117534e+17          48644.9035
                          pioverp0:      8.822274482e-06          48644.9035
                          p0pluspi:      4.760118439e+17     8.822243295e-06
                           rhopert:                    0                   0
                          rhohpert:                    0                   0
                             tpert:                    0                   0
                        MachNumber:      4.652310152e-07         2.477144092
                        deltagamma:                    0                   0
                           entropy:                    0                   0
                       entropypert:                    0                   0
                                 S:                    0                   0
                           thermal:                    0                   0
                      conductivity:                    0                   0
                   radial_velocity:          70.10997063         550958.2189
                     circ_velocity:          52.23262248         4.250346458
                            sponge:                    0                   0

**Pull request merged**
