### PR TITLE
Rebalanced reactions

### PR DESCRIPTION
**Pull request by harpolea**
This adds load balancing to the reactions, copying the method used in `Castro_react.cpp` to create a new distribution mapping based on how 'difficult' the burning is in each cell at the previous timestep.

### CODE REVIEW

**Comment by ajnonaka** [comment]
Is there a good test problem for this?  I'm trying this using 2d reacting bubble rise and am getting strange results.  The weights are constant (value of 8) everywhere except in one grid where the weights are enormous (2e9) in a region nowhere close to the burning.

**Comment by harpolea** [comment]
I wrote it to try and help `rotating_star` because the reactions were taking up 98% of the total runtime. I haven't yet done any testing of it other than checking that it didn't cause significant slowdown and that it produced the same output.

**Comment by ajnonaka** [comment]
Did it produce any speedup?  One thing I checked was to write out state_in_temp in Maestro::React using VisMF::Write to see what the new boxarray looked like.  In my test the boxarray was the same, but reacting_bubble is probably not the right problem to test it on.

**Comment by harpolea** [comment]
I've only tested its performance on my local machine with 20 MPI processes and it seemed to give a small speedup, but I haven't tested its performance on any large scale runs so it's hard to tell. I was planning on doing that when they started looking like they were burning properly (which will hopefully be soon now I've fixed the cutoff densities).

**Pull request closed without merging**
